// Code generated by mockery v2.9.4. DO NOT EDIT.

package net

import (
	log "github.com/Masterminds/log-go"
	mock "github.com/stretchr/testify/mock"

	net "github.com/thmeitz/ksqldb-go/net"
)

// HTTPClientFactory is an autogenerated mock type for the HTTPClientFactory type
type HTTPClientFactory struct {
	mock.Mock
}

// NewHTTPClient provides a mock function with given fields: options, logger
func (_m *HTTPClientFactory) NewHTTPClient(options net.Options, logger log.Logger) (*net.Client, error) {
	ret := _m.Called(options, logger)

	var r0 *net.Client
	if rf, ok := ret.Get(0).(func(net.Options, log.Logger) *net.Client); ok {
		r0 = rf(options, logger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*net.Client)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(net.Options, log.Logger) error); ok {
		r1 = rf(options, logger)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
