// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	net "github.com/thmeitz/ksqldb-go/net"
)

// TransportFactory is an autogenerated mock type for the TransportFactory type
type TransportFactory struct {
	mock.Mock
}

// NewTransport provides a mock function with given fields: options
func (_m *TransportFactory) NewTransport(options net.Options) *net.Transport {
	ret := _m.Called(options)

	var r0 *net.Transport
	if rf, ok := ret.Get(0).(func(net.Options) *net.Transport); ok {
		r0 = rf(options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*net.Transport)
		}
	}

	return r0
}
