// Code generated by mockery v2.9.4. DO NOT EDIT.

package ksqldb

import (
	mock "github.com/stretchr/testify/mock"
	net "github.com/thmeitz/ksqldb-go/net"
)

// ksqldbRequest is an autogenerated mock type for the ksqldbRequest type
type ksqldbRequest struct {
	mock.Mock
}

// handleGetRequest provides a mock function with given fields: httpClient, url
func (_m *ksqldbRequest) handleGetRequest(httpClient *net.HTTPClient, url string) (*[]byte, error) {
	ret := _m.Called(httpClient, url)

	var r0 *[]byte
	if rf, ok := ret.Get(0).(func(*net.HTTPClient, string) *[]byte); ok {
		r0 = rf(httpClient, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*net.HTTPClient, string) error); ok {
		r1 = rf(httpClient, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
