// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// KSqlDBClientCloser is an autogenerated mock type for the KSqlDBClientCloser type
type KSqlDBClientCloser struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *KSqlDBClientCloser) Close() {
	_m.Called()
}
