// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// KsqlParser is an autogenerated mock type for the KsqlParser type
type KsqlParser struct {
	mock.Mock
}

// ParseSql provides a mock function with given fields: _a0
func (_m *KsqlParser) ParseSql(_a0 string) []error {
	ret := _m.Called(_a0)

	var r0 []error
	if rf, ok := ret.Get(0).(func(string) []error); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]error)
		}
	}

	return r0
}
