// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"
	http "net/http"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// ksqldbRequest is an autogenerated mock type for the ksqldbRequest type
type ksqldbRequest struct {
	mock.Mock
}

// newQueryRequest provides a mock function with given fields: _a0, _a1
func (_m *ksqldbRequest) newQueryRequest(_a0 http.Client, _a1 io.Reader) (*http.Request, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *http.Request
	if rf, ok := ret.Get(0).(func(http.Client, io.Reader) *http.Request); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(http.Client, io.Reader) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newQueryStreamRequest provides a mock function with given fields: _a0, _a1, _a2
func (_m *ksqldbRequest) newQueryStreamRequest(_a0 http.Client, _a1 context.Context, _a2 io.Reader) (*http.Request, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 *http.Request
	if rf, ok := ret.Get(0).(func(http.Client, context.Context, io.Reader) *http.Request); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(http.Client, context.Context, io.Reader) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
