name: Go

on:
  push:
    branches: [main, develop, "feature/*"]
  pull_request:
    branches: [main, develop, "feature/*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.2'

      - name: Test
        run: |
          go test ./... -short -coverprofile=test.out -covermode=count -json > report.json

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: -no-fail -fmt=sonarqube -out secreport.json ./...

      - name: Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=thmeitz
            -Dsonar.projectKey=thmeitz_ksqldb-go
            -Dsonar.projectName=ksqldb-go
            -Dsonar.projectVersion=v0.0.5
            -Dsonar.sources=.
            -Dsonar.exclusions=**/mocks/**,**/examples/**,**/parser/ksql_base_listener.go,**/parser/ksql_lexer.go,**/parser/ksql_listener.go,**/parser/ksql_parser.go,**/report.json
            -Dsonar.tests=.
            -Dsonar.test.inclusions=**/**_test.go
            -Dsonar.go.coverage.reportPaths=test.out
            -Dsonar.go.tests.reportPaths=report.json
            -Dsonar.externalIssuesReportPaths=secreport.json
            -Dsonar.verbose=false
